FROM spark-base:1.0.3

ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_WEBUI_PORT=8080
ENV SPARK_MASTER_LOG=/spark/logs

EXPOSE 8080 7077

ENTRYPOINT /spark/bin/spark-class org.apache.spark.deploy.master.Master