# Docker Image For Data Project v1.0
FROM ubuntu:latest

# Set ENV variables
ENV SPARK_VERSION=3.3.2
ENV HADOOP_VERSION=3
ENV SCALA_VERSION=2.13.10
ENV SCALA_HOME=/usr/share/scala

# Update & install 
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y wget curl vim python3 python3-pip openjdk-8-jdk \
    && pip3 install --upgrade pip \
    && pip install spacy \
    && python3 -m spacy download en_core_web_sm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# SET JAVA HOME and PATH
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin
RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc

# Get Apache Spark
RUN wget https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    && tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    && mkdir /spark \
    && mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/* /spark \
    && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    && rm -rf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} 

# Download jar File For Skark 
RUN wget https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/3.12.12/mongo-java-driver-3.12.12.jar -O /spark/jars/mongo-java-driver-3.12.12.jar
RUN wget https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.2/mongo-spark-connector_2.12-3.0.2.jar -O /spark/jars/mongo-spark-connector_2.12-3.0.2.jar

# Apache Spark ENV
ENV SPARK_HOME=/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# Install Scala
RUN wget https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz \
    && mkdir /temp && tar -xzf "scala-${SCALA_VERSION}.tgz" -C /temp \
    && mkdir -p "${SCALA_HOME}/logs" \
    && rm "/temp/scala-${SCALA_VERSION}/bin/"*.bat \
    && mv "/temp/scala-${SCALA_VERSION}/bin" "/temp/scala-${SCALA_VERSION}/lib" "${SCALA_HOME}" \
    && ln -s "${SCALA_HOME}/bin/"* "/usr/bin/" \
    && rm -rf "/temp/"* \
    && rm scala-${SCALA_VERSION}.tgz

# Set Scala ENV
ENV SCALA_HOME=/usr/share/scala

# Set PySpark ENV
ENV PYSPARK_PYTHON=python3 \
    PYSPARK_DRIVER_PYTHON=python3 \
    PYSPARK_DRIVER_PYTHON_OPTS=python3

